export default {
    it: {
        loginFailed: 'Login Fallito',
        recoverySuccess: 'Email per il recupero della password inviata',
        recoveryError: 'Errore recupero password',
        resetSuccess: 'Reset effettuato con successo',
        resetError: 'Errore durante il reset della password',
        logoutError: 'Logout non riuscito',
        updateSuccess: 'Modifica effettuata con successo',
        updateError: 'Modifica non effettuata',
        insertSuccess: 'Inserimento effettuato con successo',
        insertError: 'Inserimento non effettuato',
        deleteSuccess: 'Cancellazione effettuata con successo',
        deleteFailed: 'Cancellazione non effettuata',
        emptySelection: 'Nessun elemento selezionato',
        passwordConfirm: 'Conferma password',
    },
    en: {
        loginFailed: 'Login Failed',
        recoverySuccess: 'Email for password recovery sent',
        recoveryError: 'Recovery password error',
        resetSuccess: 'Reset successful',
        resetError: 'Error while password reset',
        logoutError: 'Logout failed',
        updateSuccess: 'Successful modification', 
        updateError: 'Update failed',
        insertSuccess: 'Successful insert',
        insertError: 'Insert failed',
        deleteSuccess: 'Successful Delete',
        deleteFailed: 'Delete failed',
        emptySelection: 'No items selected',
        passwordConfirm: 'Password confirmation',
    }
}