export default {
    it: {
        loginFailed: 'Login Fallito',
        recoverySuccess: 'Email per il recupero della password inviata',
        recoveryError: 'Errore recupero password',
        resetSuccess: 'Reset effettuato con successo',
        resetError: 'Errore durante il reset della password',
        logoutError: 'Logout non riuscito',
        updateSuccess: 'Modifica effettuata con successo',
        updateError: 'Modifica non effettuata',
        insertSuccess: 'Inserimento effettuato con successo',
        insertError: 'Inserimento non effettuato',
        deleteSuccess: 'Cancellazione effettuata con successo',
        deleteFailed: 'Cancellazione non effettuata',
        emptySelection: 'Nessun elemento selezionato',
        passwordConfirm: 'Conferma password',
        logout: 'Logout',
        loginTitle: 'Entra con le tue credenziali',
        login: 'Login',
        recovery: 'Recupera password',
        recoveryTitle: 'Inserisci il tuo indirizzo e-mail, ti invieremo una mail per eseguire il reset',
        send: 'Invia',
        backToLogin: 'Torna al login',
        resetTitle: 'Inserisci la nuova password'
    },
    en: {
        loginFailed: 'Login Failed',
        recoverySuccess: 'Email for password recovery sent',
        recoveryError: 'Recovery password error',
        resetSuccess: 'Reset successful',
        resetError: 'Error while password reset',
        logoutError: 'Logout failed',
        updateSuccess: 'Successful modification', 
        updateError: 'Update failed',
        insertSuccess: 'Successful insert',
        insertError: 'Insert failed',
        deleteSuccess: 'Successful Delete',
        deleteFailed: 'Delete failed',
        emptySelection: 'No items selected',
        passwordConfirm: 'Password confirmation',
        logout: 'Logout',
        loginTitle: 'Log in with your credentials',
        login: 'Login',
        recovery: 'Recovery password',
        recoveryTitle: 'Enter your email address, we will send you an email to reset',
        send: 'Send',
        backToLogin: 'Back to login',
        resetTitle: 'Enter the new password',
    },
    fr: {
        loginFailed: 'Echec de la connexion',
        recoverySuccess: 'E-mail pour la récupération du mot de passe envoyé',
        recoveryError: 'Envoyer une erreur',
        resetSuccess: 'Réinitialisation du mot de passe',
        resetError: 'Erreur lors de la réinitialisation! Essayez à nouveau',
        logoutError: 'Échec de la déconnexion',
        updateSuccess: 'Modification réussie', 
        updateError: 'Erreur lors de l\'édition',
        insertSuccess: 'Entrée réussie',
        insertError: 'Erreur lors de l\'insertion',
        deleteSuccess: 'Annulation réussie',
        deleteFailed: 'Delete failed',
        emptySelection: 'Erreur lors de la suppression',
        passwordConfirm: 'Confirmer le mot de passe',
        logout: 'Déconnecter',
        loginTitle: 'Connectez-vous avec vos identifiants',
        login: 'Connectez',
        recovery: 'Mot de passe oublié',
        recoveryTitle: 'Entrez votre adresse e-mail, nous vous enverrons un e-mail pour réinitialiser',
        send: 'Soumettre',
        backToLogin: 'Retour à la connexion',
        resetTitle: 'Entrez le nouveau mot de passe'
    }
}